name: CI - Test the master branches

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Install nvm
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Install the dependencies
        run: yarn

      - name : setup the db
        run : yarn db-setup && yarn drive-fetch
        
      - name: Run the tests
        run: yarn test

      - name : Build
        run: yarn build